# Generated by Django 4.1.3 on 2023-08-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=15)),
                ('foot', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('N', 'Not Available')], default='N', max_length=1)),
                ('birth_date', models.DateField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
